# Generated by Django 5.1.4 on 2025-02-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='province',
            field=models.CharField(max_length=50, verbose_name='استان'),
        ),
    ]
